### ISSUE TITLE
update css assets to use new syntax

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-on-premise-sample-app#20]
the way we embed css in dash apps is now much improved, see https://dash.plot.ly/external-resources

we should update this repo with this new method.

@cldougl or @charleyferrari could one of you or someone from @cldougl 's team do this? It's a good opportunity to make sure that everyone is familar with the new features

**Comment by cldougl** [comment]
@michaelbabyn this is a good issue to become more familiar with the sample app that we suggest onprem users work off of to create their deployable apps.

**Comment by michaelbabyn** [comment]
closed by https://github.com/plotly/dash-on-premise-sample-app/pull/23
