### ISSUE TITLE
update version of dash and update config 

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-on-premise-sample-app#22]
with dash 0.25.0 (https://github.com/plotly/dash/blob/master/CHANGELOG.md#0250---2018-08-14), we dynamically get `requests/routes_pathname_prefix`. So, if we upgrade then we can remove this logic https://github.com/plotly/dash-on-premise-sample-app/blob/master/auth.py#L36-L45

@cldougl - can someone on your team take this?

**Comment by T4rk1n** [comment]
I am working on this, should be done soon. plotly/streambed#10766

**Comment by michaelbabyn** [comment]
closed by #25
